spring:
  main:
    allow-bean-definition-overriding : true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  redis:
    host: localhost
    port: 6379
    password: 1

jwt:
  header: ${HEADER:Authorize}
  prefix : ${PREFIX:Bearer}
  secret-key: ${JWT_SECRET_KEY:dffddefcerdfrefervrevfvvfffgbfgfgdb}
  accessExp: ${JWT_ACCESS_EXP:12000}
  refreshExp: ${JWT_REFRESH_EXP:24000}

logging:
  level:
    com.example : DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: kangsunbucket
    region:
      static: ap-northeast-2

  stack:
    auto: false
